---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: ":verify_none"
  data_path: './test/files'
  data_bags_path: './test/integration/default/data_bags/'
  encrypted_data_bag_secret_key_path: './test/integration/default/encrypted_data_bag_secret'

platforms:
  - name: centos-6
  - name: centos-7
  - name: windows-2012r2

suites:
  - name: ruby
    excludes:
      - windows-2012r2
    run_list:
      - recipe[doi_ssl_filtering]
      - recipe[doi_ssl_filtering::ruby]
    verifier:
      name: inspec
      inspec_tests:
        - name: ruby
          path: test/integration/centos6/inspec/controls/ruby_spec.rb
      controls:
        - check-ruby-ssl-with-callout
        - check-ruby-ssl-cert
      attrs:
        - test/integration/centos6/inspec/attributes/attributes.yml
    attributes: {
      "doi_ssl_filtering" : {
        "cert_locations" : [
          "file:///tmp/kitchen/data/rootCA.pem"
        ]
      }
    }

#  NOTE: Once serverspec can autodetect the backend, this won't be needed
  - name: windefault
    excludes:
      - centos-6
      - centos-7
# NOTE: serverspec no longer working
#    includes:
      - windows-2012r2
    run_list:
      - recipe[doi_ssl_filtering]
    attributes: {
      "doi_ssl_filtering" : {
        "cert_locations" : [
          "file:///Users/vagrant/AppData/Local/Temp/kitchen/data/rootCA.pem"
        ]
      }
    }

  - name: java-oracle
    excludes:
      - windows-2012r2
    run_list:
      - recipe[doi_ssl_filtering]
      - recipe[doi_ssl_filtering::ruby]
      - recipe[java]
      - recipe[doi_ssl_filtering::java]
    attributes: {
      "java" : {
          "install_flavor" : "oracle",
          "jdk_version" : "8",
          "oracle" : {
               "accept_oracle_download_terms" : true
          }
      },
      "doi_ssl_filtering" : {
        "cert_locations" : [
          "file:///tmp/kitchen/data/rootCA.pem"
        ]
      }
    }

  - name: java10-oracle
    excludes:
      - windows-2012r2
    run_list:
      - recipe[doi_ssl_filtering]
      - recipe[doi_ssl_filtering::ruby]
      - recipe[java]
      - recipe[doi_ssl_filtering::java]
    attributes: {
      "doi_ssl_filtering" : {
        "cert_locations" : [
          "file:///tmp/kitchen/data/rootCA.pem",
        ]
      },
      "java": {
          "install_flavor" : "oracle",
          "jdk_version" : "10.0.2",
          "jdk": {
            "10.0.2": {
              "bin_cmds": ["appletviewer", "jar", "javac", "javapackager", "jconsole", "jdeprscan", "jimage", "jlink", "jmod", "jshell", "jstatd", "orbd", "rmid", "serialver", "unpack200", "xjc", "idlj", "jarsigner", "javadoc", "javaws", "jcontrol", "jdeps", "jinfo", "jmap", "jps", "jstack", "jweblauncher", "pack200", "rmiregistry", "servertool", "wsgen", "jaotc", "java", "javap", "jcmd", "jdb", "jhsdb", "jjs", "jmc", "jrunscript", "jstat", "keytool", "rmic", "schemagen", "tnameserv", "wsimport"],
              "x86_64": {
                "url": "http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz",
                "checksum": "6633c20d53c50c20835364d0f3e172e0cbbce78fff81867488f22a6298fa372b"
              }
            }
          },
          "oracle" : {
               "accept_oracle_download_terms" : true
          }
       }
    }
  - name: java-openjdk
    excludes:
      - windows-2012r2
    run_list:
      - recipe[doi_ssl_filtering]
      - recipe[doi_ssl_filtering::ruby]
      - recipe[java]
      - recipe[doi_ssl_filtering::java]
    attributes: {
      "doi_ssl_filtering" : {
        "cert_locations" : [
          "file:///tmp/kitchen/data/rootCA.pem"
        ]
      },
      "java": {
        "jdk_version": "8"
      },
    }
